### ISSUE TITLE
Fields codes instead of names 

### ISSUE THREAD

**Issue by rousseldenis** [OCA/intrastat-extrastat#167]
@luc-demeyer @alexis-via I've a request from a customer:

They want some codes in the xls file instead of names for declaration :

- Source country
- Destination country
- Transaction
- Transport

As I see in inrastat definition, I think this is quite legitimate. What do you think of ?

**Comment by luc-demeyer** [comment]
@rousseldenis 
the real solution is of course a localisation module so that the excel files are only used to facilitate controls.
But I agree that the demand is legitimate and a simple adaptation of the excel template will give the result requested by your customer.
I propose to add the codes as extra columns (collated in front of the names) so that we keep the readablity of excel exports. 
Hence go ahead and create a PR to add those columns.

**Comment by rousseldenis** [comment]
> @rousseldenis 
> the real solution is of course a localisation module so that the excel files are only used to facilitate controls.
> But I agree that the demand is legitimate and a simple adaptation of the excel template will give the result requested by your customer.
> I propose to add the codes as extra columns (collated in front of the names) so that we keep the readablity of excel exports. 
> Hence go ahead and create a PR to add those columns. 

Apparently, in some countries, they are used to import directly in web interface.

**Comment by luc-demeyer** [comment]
@rousseldenis 
>>> Apparently, in some countries, they are used to import directly in web interface
Indeed. I am using it myself in our customer base for countries without localisation module. 
That's the main reason why I have added the excel export a couple of years ago.
