### ISSUE TITLE
Branch 12.0 missing

### ISSUE THREAD

**Issue by sbidoul** [OCA/intrastat-extrastat#67]
Branch 12.0 does not exist here but has been created in weblate.

Should we remove the 12.0 project from weblate?

**Comment by pedrobaeza** [comment]
This is due to a misunderstanding in the management. See details in:

https://github.com/OCA/intrastat-extrastat/pull/65#issuecomment-482205396
https://github.com/OCA/intrastat-extrastat/pull/62#issuecomment-482586481

so @luc-demeyer and @alexis-via are working to restore 11.0 branch commit history and will push 12.0 version soon. If it will be a problem, just delete 12.0 branch in Weblate.

**Comment by alexis-via** [comment]
branch 12.0 is back, so I close this issue.
